
spring:
  main:
    banner-mode: console
  datasource:
    url: jdbc:h2:mem:vteshopdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      schema-locations: classpath:db/db-schema.sql
      data-locations: classpath:db/initial-data.sql
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: user@eshop.lt
      password: user
  servlet:
    multipart:
      max-file-size: 5MB
logging:
  level:
    eu:
      codeacademy:
        vteshop:
          config: DEBUG
          filter: TRACE

